/* Elmina los datos de las tablas */

DELETE FROM HST_STA;
DELETE FROM USER_OFFER;
DELETE FROM INVOICE;
DELETE FROM PAYMENT;
DELETE FROM VALIDATION;
DELETE FROM WITHDRAW;
DELETE FROM BANK_ACCOUNT;
DELETE FROM USER_F;
DELETE FROM PLACE;
DELETE FROM LEVEL;
DELETE FROM SETTINGS;
DELETE FROM STATUS;
DELETE FROM PRODUCT;
DELETE FROM OFFER;
DELETE FROM ROLE;

