/* Elimina las tablas */ 

DROP TABLE HST_STA;
DROP TABLE USER_OFFER;
DROP TABLE PAYMENT;
DROP TABLE VALIDATION;
DROP TABLE WITHDRAW;
DROP TABLE BANK_ACCOUNT;
DROP TABLE USER_F;
DROP TABLE PLACE;
DROP TABLE LEVEL;
DROP TABLE SETTINGS;
DROP TABLE STATUS;
DROP TABLE PRODUCT;
DROP TABLE OFFER;
DROP TABLE INVOICE;
DROP TABLE ROLE;

/* Eliminar la base de datos */

DROP DATABASE consorsio_fid_3