/* ROLE INSERTS */
INSERT INTO ROLE(r_name, r_description) VALUES('client','Premileal customers.');
INSERT INTO ROLE(r_name, r_description) VALUES('administrator','Back-Office users.');

/* STATUS INSERTS */ 
INSERT INTO STATUS(sta_name, sta_description) VALUES('unverified','Bank account not available for use.');
INSERT INTO STATUS(sta_name, sta_description) VALUES('verified','Bank account available for use.');
INSERT INTO STATUS(sta_name, sta_description) VALUES('rejected','Bank account has been rejected.');
INSERT INTO STATUS(sta_name, sta_description) VALUES('blocked','Account blocked.');
INSERT INTO STATUS(sta_name, sta_description) VALUES('online','User is online.');
INSERT INTO STATUS(sta_name, sta_description) VALUES('offline','User is offline.');
INSERT INTO STATUS(sta_name, sta_description) VALUES('in process', 'Payment is being processed');
INSERT INTO STATUS(sta_name, sta_description) VALUES('approved', 'Payment has been approved');
INSERT INTO STATUS(sta_name, sta_description) VALUES('failed', 'Payment couldn\'t be proccesed');

/* LEVELS INSERTS */
INSERT INTO LEVEL(l_name, l_percentage, l_bonus, l_cost) VALUES('Basic', 0, 0, 0);
INSERT INTO LEVEL(l_name, l_percentage, l_bonus, l_cost) VALUES('Premium', 20, 0, 25);
INSERT INTO LEVEL(l_name, l_percentage, l_bonus, l_cost) VALUES('Gold', 20, 2500, 0);

/* SETTINGS INSERTS */
INSERT INTO SETTINGS(set_service_commission, set_gateway_commission, set_dolar_value, set_gold_income) VALUES(1.5, 0.75, 500, 150);

/* PLACE INSERTS */
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('AW','COUNTRY',NULL, 'Aruba');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BM','COUNTRY',NULL, 'Bermudas');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('KY','COUNTRY',NULL, 'Islas Caimán');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('AF','COUNTRY',NULL, 'Afganistán');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('AL','COUNTRY',NULL, 'Albania');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('DE','COUNTRY',NULL, 'Alemania');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('AD','COUNTRY',NULL, 'Andorra');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('AO','COUNTRY',NULL, 'Angola');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('AG','COUNTRY',NULL, 'Antigua y Barbuda');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('SA','COUNTRY',NULL, 'Arabia Saudí');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('DZ','COUNTRY',NULL, 'Argelia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('AR','COUNTRY',NULL, 'Argentina');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('AM','COUNTRY',NULL, 'Armenia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('AU','COUNTRY',NULL, 'Australia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('AT','COUNTRY',NULL, 'Austria');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('AZ','COUNTRY',NULL, 'Azerbaiyán');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BS','COUNTRY',NULL, 'Bahamas');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BD','COUNTRY',NULL, 'Bangladesh');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BB','COUNTRY',NULL, 'Barbados');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BH','COUNTRY',NULL, 'Bahréin');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BE','COUNTRY',NULL, 'Bélgica');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BZ','COUNTRY',NULL, 'Belice');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BJ','COUNTRY',NULL, 'Benin');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BY','COUNTRY',NULL, 'Bielorrusia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('MM','COUNTRY',NULL, 'Birmania');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BO','COUNTRY',NULL, 'Bolivia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BA','COUNTRY',NULL, 'Bosnia y Herzegovina');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BW','COUNTRY',NULL, 'Botsuana');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BR','COUNTRY',NULL, 'Brasil');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BN','COUNTRY',NULL, 'Brunéi');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BG','COUNTRY',NULL, 'Bulgaria');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BF','COUNTRY',NULL, 'Burkina Faso');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BI','COUNTRY',NULL, 'Burundi');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BT','COUNTRY',NULL, 'Bhután');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('CV','COUNTRY',NULL, 'Cabo Verde');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('KH','COUNTRY',NULL, 'Camboya');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('CM','COUNTRY',NULL, 'Camerún');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('CA','COUNTRY',NULL, 'Canadá');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('QA','COUNTRY',NULL, 'Catar');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('TD','COUNTRY',NULL, 'Chad');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('CL','COUNTRY',NULL, 'Chile');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('CN','COUNTRY',NULL, 'China');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('CY','COUNTRY',NULL, 'Chipre');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('VA','COUNTRY',NULL, 'Ciudad del Vaticano');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('CO','COUNTRY',NULL, 'Colombia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('KM','COUNTRY',NULL, 'Comoras');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('KP','COUNTRY',NULL, 'Corea del Norte');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('KR','COUNTRY',NULL, 'Corea del Sur');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('CI','COUNTRY',NULL, 'Costa de Marfil');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('CR','COUNTRY',NULL, 'Costa Rica');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('HR','COUNTRY',NULL, 'Croacia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('CU','COUNTRY',NULL, 'Cuba');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('DK','COUNTRY',NULL, 'Dinamarca');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('DM','COUNTRY',NULL, 'Dominica');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('EC','COUNTRY',NULL, 'Ecuador');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('EG','COUNTRY',NULL, 'Egipto');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('SV','COUNTRY',NULL, 'El Salvador');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('AE','COUNTRY',NULL, 'Emiratos Árabes Unidos');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('ER','COUNTRY',NULL, 'Eritrea');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('SK','COUNTRY',NULL, 'Eslovaquia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('SI','COUNTRY',NULL, 'Eslovenia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('ES','COUNTRY',NULL, 'España');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('US','COUNTRY',NULL, 'Estados Unidos');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('EE','COUNTRY',NULL, 'Estonia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('ET','COUNTRY',NULL, 'Etiopía');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('PH','COUNTRY',NULL, 'Filipinas');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('FI','COUNTRY',NULL, 'Finlandia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('FJ','COUNTRY',NULL, 'Fiyi');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('FR','COUNTRY',NULL, 'Francia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('GA','COUNTRY',NULL, 'Gabón');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('GM','COUNTRY',NULL, 'Gambia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('GE','COUNTRY',NULL, 'Georgia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('GH','COUNTRY',NULL, 'Ghana');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('GD','COUNTRY',NULL, 'Granada');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('GR','COUNTRY',NULL, 'Grecia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('GT','COUNTRY',NULL, 'Guatemala');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('GN','COUNTRY',NULL, 'Guinea');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('GW','COUNTRY',NULL, 'Guinea-Bissau');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('GQ','COUNTRY',NULL, 'Guinea Ecuatorial');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('GY','COUNTRY',NULL, 'Guyana');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('HT','COUNTRY',NULL, 'Haití');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('HN','COUNTRY',NULL, 'Honduras');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('HU','COUNTRY',NULL, 'Hungría');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('IN','COUNTRY',NULL, 'India');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('ID','COUNTRY',NULL, 'Indonesia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('IQ','COUNTRY',NULL, 'Irak');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('IR','COUNTRY',NULL, 'Iran');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('IE','COUNTRY',NULL, 'Irlanda');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('IS','COUNTRY',NULL, 'Islandia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('IL','COUNTRY',NULL, 'Israel');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('IT','COUNTRY',NULL, 'Italia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('JM','COUNTRY',NULL, 'Jamaica');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('JP','COUNTRY',NULL, 'Japón');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('JO','COUNTRY',NULL, 'Jordania');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('KZ','COUNTRY',NULL, 'Kazajstán');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('KE','COUNTRY',NULL, 'Kenia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('KG','COUNTRY',NULL, 'Kirguistán');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('KI','COUNTRY',NULL, 'Kiribati');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('KW','COUNTRY',NULL, 'Kuwait');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('LA','COUNTRY',NULL, 'Laos');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('LS','COUNTRY',NULL, 'Lesotho');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('LV','COUNTRY',NULL, 'Letonia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('LB','COUNTRY',NULL, 'Líbano');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('LR','COUNTRY',NULL, 'Liberia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('LY','COUNTRY',NULL, 'Libia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('LI','COUNTRY',NULL, 'Liechtenstein');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('LT','COUNTRY',NULL, 'Lituania');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('LU','COUNTRY',NULL, 'Luxemburgo');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('MK','COUNTRY',NULL, 'ARY Macedonia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('MG','COUNTRY',NULL, 'Madagascar');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('MY','COUNTRY',NULL, 'Malasia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('MW','COUNTRY',NULL, 'Malawi');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('MV','COUNTRY',NULL, 'Maldivas');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('ML','COUNTRY',NULL, 'Malí');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('MT','COUNTRY',NULL, 'Malta');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('MA','COUNTRY',NULL, 'Marruecos');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('MU','COUNTRY',NULL, 'Mauricio');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('MR','COUNTRY',NULL, 'Mauritania');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('MX','COUNTRY',NULL, 'México');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('FM','COUNTRY',NULL, 'Micronesia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('MD','COUNTRY',NULL, 'Moldavia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('MC','COUNTRY',NULL, 'Mónaco');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('MN','COUNTRY',NULL, 'Mongolia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('MZ','COUNTRY',NULL, 'Mozambique');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('NA','COUNTRY',NULL, 'Namibia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('NR','COUNTRY',NULL, 'Nauru');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('NP','COUNTRY',NULL, 'Nepal');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('NI','COUNTRY',NULL, 'Nicaragua');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('NE','COUNTRY',NULL, 'Níger');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('NG','COUNTRY',NULL, 'Nigeria');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('NO','COUNTRY',NULL, 'Noruega');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('NZ','COUNTRY',NULL, 'Nueva Zelanda');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('OM','COUNTRY',NULL, 'Omán');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('NL','COUNTRY',NULL, 'Países Bajos');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('PK','COUNTRY',NULL, 'Pakistán');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('PW','COUNTRY',NULL, 'Palau');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('PA','COUNTRY',NULL, 'Panamá');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('PG','COUNTRY',NULL, 'Papúa Nueva Guinea');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('PY','COUNTRY',NULL, 'Paraguay');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('PE','COUNTRY',NULL, 'Perú');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('PL','COUNTRY',NULL, 'Polonia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('PT','COUNTRY',NULL, 'Portugal');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('PR','COUNTRY',NULL, 'Puerto Rico');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('GB','COUNTRY',NULL, 'Reino Unido de Gran Bretaña');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('CE','COUNTRY',NULL, 'República Centroafricana');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('CK','COUNTRY',NULL, 'República Checa');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('CG','COUNTRY',NULL, 'República del Congo');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('DO','COUNTRY',NULL, 'República Dominicana');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('ZA','COUNTRY',NULL, 'República Sudafricana');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('RW','COUNTRY',NULL, 'Ruanda');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('RO','COUNTRY',NULL, 'Rumania');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('RU','COUNTRY',NULL, 'Rusia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('KN','COUNTRY',NULL, 'San Cristóbal y Nieves');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('SM','COUNTRY',NULL, 'San Marino');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('VC','COUNTRY',NULL, 'San Vicente y las Granadinas');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('LC','COUNTRY',NULL, 'Santa Lucía');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('ST','COUNTRY',NULL, 'Santo Tomé y Príncipe');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('SN','COUNTRY',NULL, 'Senegal');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('CS','COUNTRY',NULL, 'Serbia y Montenegro');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('SC','COUNTRY',NULL, 'Seychelles');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('SL','COUNTRY',NULL, 'Sierra Leona');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('SG','COUNTRY',NULL, 'Singapur');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('SY','COUNTRY',NULL, 'Siria');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('SO','COUNTRY',NULL, 'Somalia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('LK','COUNTRY',NULL, 'Sri Lanka');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('SZ','COUNTRY',NULL, 'Suazilandia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('SD','COUNTRY',NULL, 'Sudán');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('SS','COUNTRY',NULL, 'Sudán del Sur ');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('SE','COUNTRY',NULL, 'Suecia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('CH','COUNTRY',NULL, 'Suiza');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('SR','COUNTRY',NULL, 'Surinam');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('TH','COUNTRY',NULL, 'Tailandia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('TZ','COUNTRY',NULL, 'Tanzania');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('TJ','COUNTRY',NULL, 'Tayikistán');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('TL','COUNTRY',NULL, 'Timor Oriental');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('TG','COUNTRY',NULL, 'Togo');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('TO','COUNTRY',NULL, 'Tonga');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('TT','COUNTRY',NULL, 'Trinidad y Tobago');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('TN','COUNTRY',NULL, 'Túnez');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('TM','COUNTRY',NULL, 'Turkmenistán');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('TR','COUNTRY',NULL, 'Turquía');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('TV','COUNTRY',NULL, 'Tuvalu');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('UA','COUNTRY',NULL, 'Ucrania');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('UG','COUNTRY',NULL, 'Uganda');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('UY','COUNTRY',NULL, 'Uruguay');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('UZ','COUNTRY',NULL, 'Uzbekistán');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('VU','COUNTRY',NULL, 'Vanuatu');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('VE','COUNTRY',NULL, 'Venezuela');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('VN','COUNTRY',NULL, 'Vietnam');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('YE','COUNTRY',NULL, 'Yemen');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('DJ','COUNTRY',NULL, 'Yibuti');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('ZM','COUNTRY',NULL, 'Zambia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('ZW','COUNTRY',NULL, 'Zimbabue');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('MQ','COUNTRY',NULL, 'Martinica');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('MH','COUNTRY',NULL, 'Islas Marshall');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('HK','COUNTRY',NULL, 'Hong Kong');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('PS','COUNTRY',NULL, 'Palestina');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('WS','COUNTRY',NULL, 'Samoa');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('TW','COUNTRY',NULL, 'Taiwán');

/* BANK INSERTS */
INSERT INTO BANK(ba_name, fk_place_id) VALUES('Ally Bank', 264);
INSERT INTO BANK(ba_name, fk_place_id) VALUES('Bank of America', 264);
INSERT INTO BANK(ba_name, fk_place_id) VALUES('BB&T Bank', 264);
INSERT INTO BANK(ba_name, fk_place_id) VALUES('BBVA Compass', 264);
INSERT INTO BANK(ba_name, fk_place_id) VALUES('Capital One Bank', 264);
INSERT INTO BANK(ba_name, fk_place_id) VALUES('Citibank', 264);
INSERT INTO BANK(ba_name, fk_place_id) VALUES('Citizens Bank', 264);
INSERT INTO BANK(ba_name, fk_place_id) VALUES('Fifth Third Bank', 264);
INSERT INTO BANK(ba_name, fk_place_id) VALUES('HSBC Bank USA', 264);
INSERT INTO BANK(ba_name, fk_place_id) VALUES('J.P. Morgan Chase Bank', 264);
INSERT INTO BANK(ba_name, fk_place_id) VALUES('KeyBank', 264);
INSERT INTO BANK(ba_name, fk_place_id) VALUES('Kinetic Credit Union', 264);
INSERT INTO BANK(ba_name, fk_place_id) VALUES('Navy Federal Credit Union', 264);
INSERT INTO BANK(ba_name, fk_place_id) VALUES('PNC Bank', 264);
INSERT INTO BANK(ba_name, fk_place_id) VALUES('Regions Bank', 264);
INSERT INTO BANK(ba_name, fk_place_id) VALUES('SunTrust Bank', 264);
INSERT INTO BANK(ba_name, fk_place_id) VALUES('TD Bank', 264);
INSERT INTO BANK(ba_name, fk_place_id) VALUES('US Bank', 264);
INSERT INTO BANK(ba_name, fk_place_id) VALUES('USAA', 264);
INSERT INTO BANK(ba_name, fk_place_id) VALUES('Wells Fargo Bank', 264);

/* BANKS ROUTING NUMBERS INSERTS */
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('124003116', 1);

INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('051000017', 2);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('082000073', 2);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('122101706', 2);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('121000358', 2);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('123103716', 2);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('011900571', 2);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('054001204', 2);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('031202084', 2);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('063100277', 2);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('061000052', 2);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('073000176', 2);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('081904808', 2);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('071000505', 2);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('071214579', 2);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('101100045', 2);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('011000138', 2);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('052001633', 2);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('011200365', 2);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('072000805', 2);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('081000032', 2);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('053000196', 2);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('011400495', 2);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('021200339', 2);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('107000327', 2);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('122400724', 2);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('021000322', 2);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('103000017', 2);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('323070380', 2);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('011500010', 2);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('053904483', 2);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('064000020', 2);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('111000025', 2);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('125000024', 2);

INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('0622-0398-4', 3);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('0540-0154-7', 3);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('2631-9138-7', 3);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('0611-1341-5', 3);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('0839-7428-9', 3);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('0839-0068-0', 3);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('0550-0330-8', 3);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('0531-0112-1', 3);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('0312-0471-0', 3);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('0421-0226-7', 3);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('0313-0912-3', 3);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('0532-0160-7', 3);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('0642-0816-5', 3);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('1110-1769-4', 3);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('0514-0426-0', 3);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('0515-0339-4', 3);

INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('062001186', 4);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('122105744', 4);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('321170538', 4);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('107005319', 4);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('063013924', 4);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('107000783', 4);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('113010547', 4);

/*INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('', 5);*/

INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('021000089', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('021001486', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('021272655', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('022000868', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('031100209', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('091408983', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('091409571', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('113193532', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('221172610', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('254070116', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('266086554', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('271070801', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('321070007', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('321171184', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('322270055', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('322271724', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('021308176', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('021502040', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('022309239', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('022310422', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('026009645', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('026011882', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('028000082', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('028001489', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('031100908', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('052002166', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('067004764', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('067007156', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('067011993', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('091409681', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('091409704', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('091409717', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('111901962', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('111909867', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('111915686', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('113102329', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('122217056', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('122220849', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('122231935', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('122401710', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('122402159', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('226070238', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('271071402', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('271970066', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('271970312', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('271971777', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('271972064', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('311972652', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('321070104', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('321170282', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('321170444', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('322070019', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('322270262', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('322271096', 6);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('322271779', 6);

INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('211170114', 7);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('031101143', 7);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('211070175', 7);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('241070417', 7);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('011401533', 7);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('036076150', 7);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('021313103', 7);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('011500120', 7);

INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('063109935', 8);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('063113057', 8);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('067091719', 8);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('063103915', 8);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('263190812', 8);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('071923909', 8);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('074908594', 8);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('086300041', 8);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('042101190', 8);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('042100230', 8);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('083002342', 8);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('072405455', 8);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('072401404', 8);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('072400052', 8);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('081019104', 8);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('053100737', 8);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('042000314', 8);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('044002161', 8);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('041002711', 8);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('041200050', 8);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('042207735', 8);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('042202196', 8);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('043018868', 8);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('064103833', 8);

INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('021001088', 9);

INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('122100024', 10);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('322271627', 10);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('102001017', 10);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('021100361', 10);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('267084131', 10);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('061092387', 10);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('123271978', 10);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('071000013', 10);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('083000137', 10);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('065400137', 10);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('072000326', 10);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('021202337', 10);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('021000021', 10);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('022300173', 10);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('044000037', 10);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('325070760', 10);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('111000614', 10);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('124001545', 10);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('075000019', 10);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('051900366', 10);

INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('125200879', 11);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('307070267', 11);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('021300077', 11);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('222370440', 11);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('041001039', 11);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('124101555', 11);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('011200608', 11);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('123002011', 11);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('124000737', 11);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('211672531', 11);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('125000574', 11);

INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('261171671', 12);

INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('256074974', 13);

INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('', 14);

INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('062000019', 15);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('082000109', 15);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('063104668', 15);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('061101375', 15);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('073900438', 15);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('071122661', 15);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('074014213', 15);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('083901744', 15);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('065403626', 15);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('081001387', 15);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('065305436', 15);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('053012029', 15);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('053201814', 15);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('064000017', 15);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('111900785', 15);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('051009296', 15);

INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('061000104', 16);

INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('011103093', 17);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('054001725', 17);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('031201360', 17);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('067014822', 17);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('211370545', 17);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('211274450', 17);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('053902197', 17);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('011400071', 17);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('026013673', 17);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('021302567', 17);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('036001808', 17);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('011600033', 17);

INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('082000549', 18);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('122105155', 18);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('121122676', 18);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('122235821', 18);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('102101645', 18);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('102000021', 18);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('104000029', 18);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('073000545', 18);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('123103729', 18);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('071904779', 18);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('081202759', 18);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('074900783', 18);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('101000187', 18);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('042100175', 18);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('083900363', 18);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('091215927', 18);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('091300023', 18);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('091000022', 18);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('081000210', 18);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('101200453', 18);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('092900383', 18);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('107002312', 18);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('121201694', 18);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('041202582', 18);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('042000013', 18);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('123000220', 18);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('091408501', 18);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('064000059', 18);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('124302150', 18);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('125000105', 18);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('075000022', 18);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('307070115', 18);

INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('314074269', 19);

INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('125200057', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('062000080', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('111900659', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('122105278', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('121042882', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('102000076', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('021101108', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('054001220', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('031100869', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('063107513', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('061000227', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('073000228', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('124103799', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('071101307', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('074900275', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('101089292', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('055003201', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('091101455', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('091000019', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('062203751', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('092905278', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('053000219', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('091300010', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('104000058', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('021200025', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('107002192', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('321270742', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('026012881', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('041215537', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('123006800', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('031000503', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('053207766', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('091400046', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('064003768', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('112000066', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('124002971', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('051400549', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('125008547', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('075911988', 20);
INSERT INTO ROUTING_NUMBER(ro_number, fk_bank_id) VALUES('102301092', 20);