/* ROLE INSERTS */
INSERT INTO ROLE(r_name,r_description) VALUES('client','Premileal customers.');
INSERT INTO ROLE(r_name,r_description) VALUES('administrator','Back-Office users.');

/* STATUS INSERTS */ 
INSERT INTO STATUS(sta_name,sta_description) VALUES('unverified','Bank account not available for use.');
INSERT INTO STATUS(sta_name,sta_description) VALUES('verified','Bank account available for use.');
INSERT INTO STATUS(sta_name,sta_description) VALUES('rejected','Bank account has been rejected.');
INSERT INTO STATUS(sta_name,sta_description) VALUES('blocked','Account blocked.');
INSERT INTO STATUS(sta_name,sta_description) VALUES('online','User is online.');
INSERT INTO STATUS(sta_name,sta_description) VALUES('offline','User is offline.');

/* LEVELS INSERTS */
INSERT INTO LEVEL(l_name, l_percentage, l_bonus, l_cost) VALUES('Basic', 0, 0, 0);
INSERT INTO LEVEL(l_name, l_percentage, l_bonus, l_cost) VALUES('Premium', 20, 0, 25);
INSERT INTO LEVEL(l_name, l_percentage, l_bonus, l_cost) VALUES('Gold', 20, 2500, 0);

/* SETTINGS INSERTS */
INSERT INTO SETTINGS(set_service_commission, set_gateway_commission, set_dolar_value, set_gold_income) VALUES(1.5, 0.75, 500, 150);

/* PLACE INSERTS */
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('AW','COUNTRY',NULL, 'Aruba');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BM','COUNTRY',NULL, 'Bermudas');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('KY','COUNTRY',NULL, 'Islas Caimán');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('AF','COUNTRY',NULL, 'Afganistán');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('AL','COUNTRY',NULL, 'Albania');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('DE','COUNTRY',NULL, 'Alemania');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('AD','COUNTRY',NULL, 'Andorra');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('AO','COUNTRY',NULL, 'Angola');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('AG','COUNTRY',NULL, 'Antigua y Barbuda');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('SA','COUNTRY',NULL, 'Arabia Saudí');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('DZ','COUNTRY',NULL, 'Argelia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('AR','COUNTRY',NULL, 'Argentina');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('AM','COUNTRY',NULL, 'Armenia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('AU','COUNTRY',NULL, 'Australia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('AT','COUNTRY',NULL, 'Austria');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('AZ','COUNTRY',NULL, 'Azerbaiyán');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BS','COUNTRY',NULL, 'Bahamas');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BD','COUNTRY',NULL, 'Bangladesh');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BB','COUNTRY',NULL, 'Barbados');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BH','COUNTRY',NULL, 'Bahréin');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BE','COUNTRY',NULL, 'Bélgica');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BZ','COUNTRY',NULL, 'Belice');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BJ','COUNTRY',NULL, 'Benin');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BY','COUNTRY',NULL, 'Bielorrusia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('MM','COUNTRY',NULL, 'Birmania');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BO','COUNTRY',NULL, 'Bolivia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BA','COUNTRY',NULL, 'Bosnia y Herzegovina');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BW','COUNTRY',NULL, 'Botsuana');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BR','COUNTRY',NULL, 'Brasil');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BN','COUNTRY',NULL, 'Brunéi');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BG','COUNTRY',NULL, 'Bulgaria');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BF','COUNTRY',NULL, 'Burkina Faso');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BI','COUNTRY',NULL, 'Burundi');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('BT','COUNTRY',NULL, 'Bhután');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('CV','COUNTRY',NULL, 'Cabo Verde');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('KH','COUNTRY',NULL, 'Camboya');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('CM','COUNTRY',NULL, 'Camerún');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('CA','COUNTRY',NULL, 'Canadá');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('QA','COUNTRY',NULL, 'Catar');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('TD','COUNTRY',NULL, 'Chad');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('CL','COUNTRY',NULL, 'Chile');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('CN','COUNTRY',NULL, 'China');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('CY','COUNTRY',NULL, 'Chipre');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('VA','COUNTRY',NULL, 'Ciudad del Vaticano');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('CO','COUNTRY',NULL, 'Colombia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('KM','COUNTRY',NULL, 'Comoras');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('KP','COUNTRY',NULL, 'Corea del Norte');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('KR','COUNTRY',NULL, 'Corea del Sur');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('CI','COUNTRY',NULL, 'Costa de Marfil');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('CR','COUNTRY',NULL, 'Costa Rica');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('HR','COUNTRY',NULL, 'Croacia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('CU','COUNTRY',NULL, 'Cuba');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('DK','COUNTRY',NULL, 'Dinamarca');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('DM','COUNTRY',NULL, 'Dominica');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('EC','COUNTRY',NULL, 'Ecuador');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('EG','COUNTRY',NULL, 'Egipto');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('SV','COUNTRY',NULL, 'El Salvador');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('AE','COUNTRY',NULL, 'Emiratos Árabes Unidos');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('ER','COUNTRY',NULL, 'Eritrea');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('SK','COUNTRY',NULL, 'Eslovaquia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('SI','COUNTRY',NULL, 'Eslovenia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('ES','COUNTRY',NULL, 'España');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('US','COUNTRY',NULL, 'Estados Unidos');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('EE','COUNTRY',NULL, 'Estonia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('ET','COUNTRY',NULL, 'Etiopía');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('PH','COUNTRY',NULL, 'Filipinas');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('FI','COUNTRY',NULL, 'Finlandia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('FJ','COUNTRY',NULL, 'Fiyi');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('FR','COUNTRY',NULL, 'Francia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('GA','COUNTRY',NULL, 'Gabón');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('GM','COUNTRY',NULL, 'Gambia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('GE','COUNTRY',NULL, 'Georgia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('GH','COUNTRY',NULL, 'Ghana');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('GD','COUNTRY',NULL, 'Granada');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('GR','COUNTRY',NULL, 'Grecia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('GT','COUNTRY',NULL, 'Guatemala');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('GN','COUNTRY',NULL, 'Guinea');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('GW','COUNTRY',NULL, 'Guinea-Bissau');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('GQ','COUNTRY',NULL, 'Guinea Ecuatorial');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('GY','COUNTRY',NULL, 'Guyana');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('HT','COUNTRY',NULL, 'Haití');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('HN','COUNTRY',NULL, 'Honduras');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('HU','COUNTRY',NULL, 'Hungría');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('IN','COUNTRY',NULL, 'India');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('ID','COUNTRY',NULL, 'Indonesia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('IQ','COUNTRY',NULL, 'Irak');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('IR','COUNTRY',NULL, 'Iran');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('IE','COUNTRY',NULL, 'Irlanda');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('IS','COUNTRY',NULL, 'Islandia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('IL','COUNTRY',NULL, 'Israel');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('IT','COUNTRY',NULL, 'Italia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('JM','COUNTRY',NULL, 'Jamaica');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('JP','COUNTRY',NULL, 'Japón');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('JO','COUNTRY',NULL, 'Jordania');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('KZ','COUNTRY',NULL, 'Kazajstán');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('KE','COUNTRY',NULL, 'Kenia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('KG','COUNTRY',NULL, 'Kirguistán');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('KI','COUNTRY',NULL, 'Kiribati');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('KW','COUNTRY',NULL, 'Kuwait');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('LA','COUNTRY',NULL, 'Laos');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('LS','COUNTRY',NULL, 'Lesotho');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('LV','COUNTRY',NULL, 'Letonia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('LB','COUNTRY',NULL, 'Líbano');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('LR','COUNTRY',NULL, 'Liberia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('LY','COUNTRY',NULL, 'Libia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('LI','COUNTRY',NULL, 'Liechtenstein');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('LT','COUNTRY',NULL, 'Lituania');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('LU','COUNTRY',NULL, 'Luxemburgo');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('MK','COUNTRY',NULL, 'ARY Macedonia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('MG','COUNTRY',NULL, 'Madagascar');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('MY','COUNTRY',NULL, 'Malasia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('MW','COUNTRY',NULL, 'Malawi');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('MV','COUNTRY',NULL, 'Maldivas');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('ML','COUNTRY',NULL, 'Malí');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('MT','COUNTRY',NULL, 'Malta');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('MA','COUNTRY',NULL, 'Marruecos');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('MU','COUNTRY',NULL, 'Mauricio');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('MR','COUNTRY',NULL, 'Mauritania');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('MX','COUNTRY',NULL, 'México');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('FM','COUNTRY',NULL, 'Micronesia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('MD','COUNTRY',NULL, 'Moldavia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('MC','COUNTRY',NULL, 'Mónaco');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('MN','COUNTRY',NULL, 'Mongolia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('MZ','COUNTRY',NULL, 'Mozambique');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('NA','COUNTRY',NULL, 'Namibia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('NR','COUNTRY',NULL, 'Nauru');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('NP','COUNTRY',NULL, 'Nepal');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('NI','COUNTRY',NULL, 'Nicaragua');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('NE','COUNTRY',NULL, 'Níger');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('NG','COUNTRY',NULL, 'Nigeria');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('NO','COUNTRY',NULL, 'Noruega');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('NZ','COUNTRY',NULL, 'Nueva Zelanda');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('OM','COUNTRY',NULL, 'Omán');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('NL','COUNTRY',NULL, 'Países Bajos');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('PK','COUNTRY',NULL, 'Pakistán');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('PW','COUNTRY',NULL, 'Palau');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('PA','COUNTRY',NULL, 'Panamá');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('PG','COUNTRY',NULL, 'Papúa Nueva Guinea');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('PY','COUNTRY',NULL, 'Paraguay');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('PE','COUNTRY',NULL, 'Perú');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('PL','COUNTRY',NULL, 'Polonia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('PT','COUNTRY',NULL, 'Portugal');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('PR','COUNTRY',NULL, 'Puerto Rico');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('GB','COUNTRY',NULL, 'Reino Unido de Gran Bretaña');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('CE','COUNTRY',NULL, 'República Centroafricana');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('CK','COUNTRY',NULL, 'República Checa');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('CG','COUNTRY',NULL, 'República del Congo');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('DO','COUNTRY',NULL, 'República Dominicana');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('ZA','COUNTRY',NULL, 'República Sudafricana');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('RW','COUNTRY',NULL, 'Ruanda');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('RO','COUNTRY',NULL, 'Rumania');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('RU','COUNTRY',NULL, 'Rusia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('KN','COUNTRY',NULL, 'San Cristóbal y Nieves');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('SM','COUNTRY',NULL, 'San Marino');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('VC','COUNTRY',NULL, 'San Vicente y las Granadinas');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('LC','COUNTRY',NULL, 'Santa Lucía');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('ST','COUNTRY',NULL, 'Santo Tomé y Príncipe');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('SN','COUNTRY',NULL, 'Senegal');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('CS','COUNTRY',NULL, 'Serbia y Montenegro');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('SC','COUNTRY',NULL, 'Seychelles');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('SL','COUNTRY',NULL, 'Sierra Leona');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('SG','COUNTRY',NULL, 'Singapur');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('SY','COUNTRY',NULL, 'Siria');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('SO','COUNTRY',NULL, 'Somalia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('LK','COUNTRY',NULL, 'Sri Lanka');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('SZ','COUNTRY',NULL, 'Suazilandia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('SD','COUNTRY',NULL, 'Sudán');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('SS','COUNTRY',NULL, 'Sudán del Sur ');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('SE','COUNTRY',NULL, 'Suecia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('CH','COUNTRY',NULL, 'Suiza');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('SR','COUNTRY',NULL, 'Surinam');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('TH','COUNTRY',NULL, 'Tailandia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('TZ','COUNTRY',NULL, 'Tanzania');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('TJ','COUNTRY',NULL, 'Tayikistán');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('TL','COUNTRY',NULL, 'Timor Oriental');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('TG','COUNTRY',NULL, 'Togo');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('TO','COUNTRY',NULL, 'Tonga');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('TT','COUNTRY',NULL, 'Trinidad y Tobago');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('TN','COUNTRY',NULL, 'Túnez');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('TM','COUNTRY',NULL, 'Turkmenistán');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('TR','COUNTRY',NULL, 'Turquía');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('TV','COUNTRY',NULL, 'Tuvalu');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('UA','COUNTRY',NULL, 'Ucrania');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('UG','COUNTRY',NULL, 'Uganda');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('UY','COUNTRY',NULL, 'Uruguay');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('UZ','COUNTRY',NULL, 'Uzbekistán');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('VU','COUNTRY',NULL, 'Vanuatu');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('VE','COUNTRY',NULL, 'Venezuela');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('VN','COUNTRY',NULL, 'Vietnam');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('YE','COUNTRY',NULL, 'Yemen');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('DJ','COUNTRY',NULL, 'Yibuti');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('ZM','COUNTRY',NULL, 'Zambia');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('ZW','COUNTRY',NULL, 'Zimbabue');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('MQ','COUNTRY',NULL, 'Martinica');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('MH','COUNTRY',NULL, 'Islas Marshall');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('HK','COUNTRY',NULL, 'Hong Kong');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('PS','COUNTRY',NULL, 'Palestina');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('WS','COUNTRY',NULL, 'Samoa');
INSERT INTO PLACE (p_acronym, p_type, fk_place_id, p_name) VALUES ('TW','COUNTRY',NULL, 'Taiwán');