/* Asignar nivel basico a Usuario */

CREATE OR REPLACE FUNCTION ASSIGN_LEVEL()
	RETURNS TRIGGER AS
	$BODY$
	BEGIN 
		UPDATE USER_F
		SET l_u_id = 1
		WHERE u_id = NEW.u_id;

		RETURN NEW;
	END;
	$BODY$
LANGUAGE plpgsql;

CREATE TRIGGER EXEC_ASSIGN_LEVEL
	AFTER INSERT ON USER_F
	FOR EACH ROW
		EXECUTE PROCEDURE ASSIGN_LEVEL();