/* --------------- GENERATE USER FIRST STATUS ------------------ */
CREATE TRIGGER EXEC_GENERATE_USER_FIRST_STATUS
	AFTER INSERT ON USER_F
	FOR EACH ROW
		EXECUTE PROCEDURE GENERATE_USER_FIRST_STATUS()

/* --------------- ASSIGN LEVEL ------------------ */
CREATE TRIGGER EXEC_ASSIGN_LEVEL
	AFTER INSERT ON USER_F
	FOR EACH ROW
		EXECUTE PROCEDURE ASSIGN_LEVEL();