/* --------------- GENERATE USER FIRST STATUS ------------------ */
CREATE TRIGGER EXEC_GENERATE_USER_FIRST_STATUS
	AFTER INSERT ON USER_F
	FOR EACH ROW
		EXECUTE PROCEDURE GENERATE_USER_FIRST_STATUS();

/* --------------- BANK ACCOUNT UNVERIFIED ------------------ */
CREATE TRIGGER EXEC_GENERATE_USER_FIRST_STATUS
	AFTER INSERT ON BANK_ACCOUNT
	FOR EACH ROW
		EXECUTE PROCEDURE GENERATE_BANK_ACCOUNT_FIRST_STATUS();

/* --------------- PROCCESSING PAYMENT ------------------ */
CREATE TRIGGER EXEC_GENERATE_PAYMENT_FIRST_STATUS
	AFTER INSERT ON PAYMENT
	FOR EACH ROW
		EXECUTE PROCEDURE GENERATE_PAYMENT_FIRST_STATUS();		